-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 11:00:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE `CLIENTE` (
  `IDCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NMCLIENTE` VARCHAR(200) NOT NULL,
  `TIPOCLIENTE` VARCHAR(8) NOT NULL,
  `CPF/CNPJ` INT(16) NOT NULL,
  PRIMARY KEY (`IDCLIENTE`))

DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`EMAIL`
-- -----------------------------------------------------
CREATE TABLE `EMAIL` (
  `IDEMAIL` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(200) NULL,
  `CLIENTE_IDCLIENTE` INT NOT NULL,
  PRIMARY KEY (`IDEMAIL`, `CLIENTE_IDCLIENTE`),
  INDEX `fk_EMAIL_CLIENTE1_idx` (`CLIENTE_IDCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_EMAIL_CLIENTE1`
    FOREIGN KEY (`CLIENTE_IDCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`IDCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONE`
-- -----------------------------------------------------
CREATE TABLE `TELEFONE` (
  `IDTELEFONE` INT NOT NULL AUTO_INCREMENT,
  `TELEFONE` INT(11) NOT NULL,
  `CLIENTE_IDCLIENTE` INT NOT NULL,
  PRIMARY KEY (`IDTELEFONE`, `CLIENTE_IDCLIENTE`),
  INDEX `fk_TELEFONE_CLIENTE1_idx` (`CLIENTE_IDCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFONE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_IDCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`IDCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE `ENDERECO` (
  `IDENDERECO` INT NOT NULL AUTO_INCREMENT,
  `CEP` INT(8) NULL,
  `NMRUA` VARCHAR(100) NOT NULL,
  `NRCASA` INT(5) NOT NULL,
  `COMPLEMENTO` VARCHAR(50) NULL,
  `ESTADO` VARCHAR(50) NOT NULL,
  `CIDADE` VARCHAR(50) NOT NULL,
  `BAIRRO` VARCHAR(50) NOT NULL,
  `CLIENTE_IDCLIENTE` INT NOT NULL,
  PRIMARY KEY (`IDENDERECO`, `CLIENTE_IDCLIENTE`),
  INDEX `fk_ENDERECO_CLIENTE1_idx` (`CLIENTE_IDCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_IDCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`IDCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`MOTO`
-- -----------------------------------------------------
CREATE TABLE `MOTO` (
  `IDMOTO` INT NOT NULL AUTO_INCREMENT,
  `MARCA` VARCHAR(20) NOT NULL,
  `MODELO` VARCHAR(20) NOT NULL,
  `COR` VARCHAR(50) NULL,
  `COMBUSTIVEL` VARCHAR(8) NOT NULL,
  `POTENCIA` VARCHAR(10) NOT NULL,
  `NRCHASSIS` INT(17) NOT NULL,
  `CLIENTE_IDCLIENTE` INT NOT NULL,
  PRIMARY KEY (`IDMOTO`),
  INDEX `fk_MOTO_CLIENTE1_idx` (`CLIENTE_IDCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_MOTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_IDCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`IDCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`NOTA_FISCAL`
-- -----------------------------------------------------
CREATE TABLE `NOTA_FISCAL` (
  `IDNOTAFISCAL` INT NOT NULL AUTO_INCREMENT,
  `DTNOTA` DATE NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `MOTO_IDMOTO` INT NOT NULL,
  PRIMARY KEY (`IDNOTAFISCAL`),
  INDEX `fk_NOTA_FISCAL_MOTO1_idx` (`MOTO_IDMOTO` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_FISCAL_MOTO1`
    FOREIGN KEY (`MOTO_IDMOTO`)
    REFERENCES `mydb`.`MOTO` (`IDMOTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICO`
-- -----------------------------------------------------
CREATE TABLE `SERVICO` (
  `IDSERVICO` INT NOT NULL AUTO_INCREMENT,
  `NMSERVICO` VARCHAR(50) NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `DESCRICAO` VARCHAR(100) NULL,
  PRIMARY KEY (`IDSERVICO`))
;


-- -----------------------------------------------------
-- Table `mydb`.`PECA`
-- -----------------------------------------------------
CREATE TABLE `PECA` (
  `IDPECA` INT NOT NULL AUTO_INCREMENT,
  `NMPECA` VARCHAR(50) NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `DESCRICAO` VARCHAR(100) NULL,
  PRIMARY KEY (`IDPECA`))
;


-- -----------------------------------------------------
-- Table `mydb`.`NOTA_FISCAL_SERVICO`
-- -----------------------------------------------------
CREATE TABLE `NOTA_FISCAL_SERVICO` (
  `NOTA_FISCAL_IDNOTAFISCAL` INT NOT NULL,
  `SERVICO_IDSERVICO` INT NOT NULL,
  PRIMARY KEY (`NOTA_FISCAL_IDNOTAFISCAL`, `SERVICO_IDSERVICO`),
  INDEX `fk_NOTA_FISCAL_has_SERVICO_SERVICO1_idx` (`SERVICO_IDSERVICO` ASC) VISIBLE,
  INDEX `fk_NOTA_FISCAL_has_SERVICO_NOTA_FISCAL1_idx` (`NOTA_FISCAL_IDNOTAFISCAL` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_FISCAL_has_SERVICO_NOTA_FISCAL1`
    FOREIGN KEY (`NOTA_FISCAL_IDNOTAFISCAL`)
    REFERENCES `mydb`.`NOTA_FISCAL` (`IDNOTAFISCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_FISCAL_has_SERVICO_SERVICO1`
    FOREIGN KEY (`SERVICO_IDSERVICO`)
    REFERENCES `mydb`.`SERVICO` (`IDSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`PECA_SERVICO`
-- -----------------------------------------------------
CREATE TABLE `PECA_SERVICO` (
  `PECA_IDPECA` INT NOT NULL,
  `SERVICO_IDSERVICO` INT NOT NULL,
  `QUANTIDADE` INT(3) NOT NULL,
  PRIMARY KEY (`PECA_IDPECA`, `SERVICO_IDSERVICO`),
  INDEX `fk_PECA_has_SERVICO_SERVICO2_idx` (`SERVICO_IDSERVICO` ASC) VISIBLE,
  INDEX `fk_PECA_has_SERVICO_PECA2_idx` (`PECA_IDPECA` ASC) VISIBLE,
  CONSTRAINT `fk_PECA_has_SERVICO_PECA2`
    FOREIGN KEY (`PECA_IDPECA`)
    REFERENCES `mydb`.`PECA` (`IDPECA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PECA_has_SERVICO_SERVICO2`
    FOREIGN KEY (`SERVICO_IDSERVICO`)
    REFERENCES `mydb`.`SERVICO` (`IDSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
